/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.3/userguide/multi_project_builds.html
 */

pluginManagement {
	resolutionStrategy {
			eachPlugin {
					if (requested.id.id.startsWith("com.cognifide.aem.")) {
							useVersion("11.0.11")
					}
			}
	}
}

rootProject.name = "aem-test"
